name: Docker Hub description
on:
  push:
    branches: [master]
    paths:
      - docker/README.md
      - .github/workflows/dockerhub-readme.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: 2fauth
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: 2fauth/2fauth
          short-description: A web app to manage your Two-Factor Authentication (2FA) accounts and generate their security codes
          readme-filepath: docker/README.md
